### ISSUE TITLE
NOTICE and NOTICE.txt files are not used to find licenses

### ISSUE THREAD

**Issue by JimBee** [MikeMoore63/spdx_matcher#2]
License information is sometimes present in a NOTICE or NOTICE.txt files. This information may not be present in LICENSE files.
For example kibana is licensed under Apache 2.0, ELv2 and SSPL-1.0. 
See https://github.com/elastic/kibana/tree/main/licenses

The kibana docker image was scanned using spdx_matcher as follows:
1. kibana:7.17.5 pulled from Docker hub and saved as a tar file.
2. Tar file plus nested tars for each layer extracted.
3. Scan of the kibana image filesystem ran (I modified demo.py to point at the extracted image directory)

The scan did not detect SSPL.

Modifying the regex to scan both LICENSE and NOTICE files does not result in SSPL being detected.
I.e. I added a new regex NOTICE_RE = r'^.*NOTICE$|^.*NOTICE.*\.(?!(exe|dll|go|c|h|py|pyc|rb|sh|sql|jsonl)$)([^.]+$)'

In addition the NOTICE.txt file is large (1.1MB), see attached. This causes the scan to take a long time to run (~15 minutes).

Location of NOTICE.txt:
Layer: 19d15b3110bdbf162b02a4940a42c88dc85992293b2da8f4ce38c5a0a86f3c1e
/usr/share/kibana/NOTICE.txt

The SSPL license is also mentioned in some package.json files. E.g. usr/share/kibana/node_modules/@kbn/securitysolution-io-ts-alerting-types/package.json
{
  "name": "@kbn/securitysolution-io-ts-alerting-types",
  "version": "1.0.0",
  "description": "io ts utilities and types to be shared with plugins from the security solution project",
  "license": "SSPL-1.0 OR Elastic License 2.0",
  "browser": "./target_web/index.js",
  "main": "./target_node/index.js",
  "types": "./target_types/index.d.ts",
  "private": true
}

[NOTICE.txt](https://github.com/MikeMoore63/spdx_matcher/files/11039359/NOTICE.txt)

**Comment by mike-m-hsbc** [comment]
Version 0.0.11 added SSPL parsing support so was principal blocker for the demo app you could change to add scope.

Closing as the major blocker is resolved.
